# Generated by Django 2.2.11 on 2020-03-27 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cmnt', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='LeaDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('source', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('url', models.URLField(max_length=100)),
                ('domain', models.CharField(max_length=100)),
                ('keyword', models.CharField(max_length=100)),
                ('attachment', models.CharField(max_length=100)),
                ('technology', models.CharField(max_length=100)),
                ('estimated_budget', models.PositiveIntegerField()),
                ('referredby', models.CharField(max_length=100)),
                ('assignto', models.CharField(max_length=100)),
                ('status', models.CharField(default='new', max_length=100)),
                ('rejectreason', models.TextField(blank=True)),
                ('fullname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('company', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('skypeid', models.CharField(max_length=100, unique=True)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lead1.Comment')),
            ],
        ),
    ]
